INSERT INTO users (id, email, password, full_name, role, created_at)
SELECT 1, 'seed.recruiter@smartjobportal.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'Smart Job Portal Demo Recruiter', 'RECRUITER', CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'seed.recruiter@smartjobportal.com');

INSERT INTO jobs (title, description, company, location, job_type, recruiter_id, created_at, active) VALUES
('Backend Java Engineer', 'Build scalable Spring Boot APIs, services, and integrations for a high-growth platform.', 'Nexa Systems', 'Bengaluru, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Frontend React Developer', 'Create accessible React interfaces and reusable design-system components.', 'BrightLayer', 'Remote - India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Full Stack Software Engineer', 'Deliver customer-facing features across a Java backend and modern web frontend.', 'OrbitWorks', 'Hyderabad, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Java Microservices Developer', 'Design resilient microservices using Java, Spring Cloud, Docker, and Kubernetes.', 'CloudHarbor', 'Pune, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('QA Automation Engineer', 'Build reliable API and browser automation suites for continuous delivery.', 'QualityNest', 'Chennai, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('DevOps Platform Engineer', 'Automate cloud infrastructure, deployment pipelines, and observability.', 'StackForge', 'Remote - India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Cloud Solutions Architect', 'Lead secure and scalable AWS architecture for enterprise workloads.', 'SkyGrid Technologies', 'Mumbai, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Site Reliability Engineer', 'Improve availability, incident response, and performance of production systems.', 'ReliantCloud', 'Delhi NCR, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Data Engineer', 'Develop batch and streaming pipelines that turn operational data into trusted datasets.', 'DataSpring', 'Bengaluru, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Analytics Engineer', 'Model warehouse data and publish dependable metrics for product teams.', 'MetricWave', 'Remote - India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Machine Learning Engineer', 'Train and productionize recommendation and forecasting models.', 'InsightForge', 'Bengaluru, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('NLP Research Engineer', 'Build language understanding systems for search and document intelligence.', 'Lumen AI', 'Hyderabad, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Data Scientist', 'Use experimentation and statistical modeling to guide product decisions.', 'SignalPeak', 'Pune, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('AI Product Engineer', 'Turn generative AI prototypes into secure, observable product experiences.', 'Cortex Labs', 'Remote - India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Computer Vision Engineer', 'Develop image detection and classification pipelines for industrial customers.', 'VisionArc', 'Chennai, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Security Engineer', 'Protect applications through threat modeling, monitoring, and secure engineering.', 'ShieldStack', 'Bengaluru, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Application Security Analyst', 'Find and remediate vulnerabilities across web and API platforms.', 'Trustline Digital', 'Noida, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Identity and Access Engineer', 'Build authentication, authorization, and identity lifecycle solutions.', 'AccessPoint', 'Remote - India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Security Operations Analyst', 'Monitor security events and coordinate incident response with engineering teams.', 'FortressOne', 'Mumbai, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Cloud Security Consultant', 'Define cloud security controls, guardrails, and compliance automation.', 'SecureOrbit', 'Gurugram, India', 'CONTRACT', 1, CURRENT_TIMESTAMP, TRUE),
('Product Manager - SaaS', 'Own roadmap discovery and delivery for a collaborative SaaS product.', 'ProductLane', 'Bengaluru, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Technical Product Manager', 'Translate complex platform capabilities into measurable customer outcomes.', 'Northstar Software', 'Remote - India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Product Operations Manager', 'Improve product planning, launch readiness, and cross-functional execution.', 'LaunchCraft', 'Hyderabad, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Growth Product Manager', 'Run experiments that improve activation, retention, and monetization.', 'ScaleMint', 'Mumbai, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Business Analyst', 'Map business processes and convert stakeholder needs into actionable requirements.', 'BridgePoint Consulting', 'Pune, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Technical Program Manager', 'Coordinate multi-team programs, risks, dependencies, and delivery milestones.', 'ProgramWorks', 'Chennai, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Scrum Master', 'Facilitate agile delivery and help teams continuously improve their ways of working.', 'AgileHarbor', 'Remote - India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Program Delivery Lead', 'Lead strategic technology programs across distributed engineering teams.', 'Summit Delivery', 'Delhi NCR, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Solutions Consultant', 'Design technical solutions and guide customers through successful adoption.', 'SolutionSphere', 'Bengaluru, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Customer Success Manager', 'Help strategic customers achieve measurable outcomes with our platform.', 'CustomerFirst', 'Remote - India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Technical Support Engineer', 'Resolve complex customer issues through debugging, APIs, and clear communication.', 'HelpDesk Pro', 'Hyderabad, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Implementation Consultant', 'Configure enterprise workflows and lead customer implementation projects.', 'DeployRight', 'Pune, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Salesforce Administrator', 'Manage CRM configuration, automation, data quality, and user enablement.', 'RevOps Cloud', 'Mumbai, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Salesforce Developer', 'Build Apex services, Lightning components, and integrations for sales teams.', 'CRMWorks', 'Remote - India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('SAP Functional Consultant', 'Configure finance and supply-chain processes for enterprise customers.', 'EnterpriseAxis', 'Bengaluru, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('ERP Integration Specialist', 'Connect ERP workflows with modern APIs and business applications.', 'Connectiva', 'Chennai, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Financial Analyst', 'Build forecasts, dashboards, and analysis for a growing technology business.', 'CapitalBridge', 'Mumbai, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Risk Analyst', 'Assess operational and financial risks and recommend practical controls.', 'RiskWise', 'Gurugram, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Investment Research Associate', 'Research markets, companies, and trends to support investment decisions.', 'BlueLedger Capital', 'Mumbai, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Finance Systems Analyst', 'Improve reporting systems and automate recurring finance processes.', 'LedgerLoop', 'Remote - India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Marketing Manager', 'Develop integrated campaigns that build awareness and qualified pipeline.', 'BrandCurrent', 'Bengaluru, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Content Strategist', 'Create an editorial strategy for technical audiences and product education.', 'StoryStack', 'Remote - India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('SEO Specialist', 'Grow organic acquisition through technical SEO, content, and measurement.', 'SearchFoundry', 'Pune, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Performance Marketing Analyst', 'Optimize paid acquisition through experiments, attribution, and reporting.', 'AdSignal', 'Delhi NCR, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Community Manager', 'Build an engaged professional community through events and useful content.', 'CommonGround', 'Hyderabad, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('UX Researcher', 'Plan qualitative and quantitative research that informs product decisions.', 'HumanScale', 'Bengaluru, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Product Designer', 'Design clear workflows and polished experiences for complex business tools.', 'FormFactor', 'Remote - India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('UX Writer', 'Shape helpful product language and consistent content patterns across experiences.', 'WordCraft', 'Mumbai, India', 'CONTRACT', 1, CURRENT_TIMESTAMP, TRUE),
('Visual Designer', 'Create visual systems for campaigns, product surfaces, and brand communications.', 'CanvasPeak', 'Pune, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Design Systems Lead', 'Own a scalable component library and partner with product engineering.', 'InterfaceFoundry', 'Bengaluru, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Recruitment Specialist', 'Source and close exceptional technical talent for a growing organization.', 'TalentOrbit', 'Remote - India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('People Operations Partner', 'Build thoughtful people processes across the employee lifecycle.', 'PeoplePulse', 'Hyderabad, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Learning and Development Manager', 'Create programs that grow leadership, technical, and collaboration skills.', 'GrowWell', 'Bengaluru, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Compensation Analyst', 'Maintain competitive compensation frameworks and people analytics.', 'WorkforceIQ', 'Mumbai, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Legal Operations Specialist', 'Improve contract workflows, legal tooling, and matter management.', 'ClauseWorks', 'Delhi NCR, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Commercial Counsel', 'Advise product and sales teams on technology and commercial agreements.', 'CounselBridge', 'Bengaluru, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Compliance Manager', 'Design compliance programs for privacy, security, and regulated operations.', 'ComplyCore', 'Remote - India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Privacy Analyst', 'Support privacy assessments, data inventories, and regulatory readiness.', 'PrivacyLane', 'Pune, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Operations Manager', 'Improve daily business operations through process design and measurement.', 'OperateWell', 'Chennai, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Supply Chain Analyst', 'Use data to improve inventory, planning, and supplier performance.', 'FlowChain', 'Mumbai, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Procurement Specialist', 'Manage sourcing, vendor relationships, and strategic purchasing programs.', 'SourcePilot', 'Bengaluru, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Logistics Coordinator', 'Coordinate shipments, partners, and service levels across regional operations.', 'RouteWorks', 'Hyderabad, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Healthcare Product Manager', 'Improve digital tools that help providers deliver better patient care.', 'CareSphere', 'Bengaluru, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Clinical Data Analyst', 'Turn clinical and operational data into insights for healthcare teams.', 'MedData Labs', 'Pune, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Health Information Specialist', 'Maintain accurate health information workflows and reporting standards.', 'WellnessGrid', 'Remote - India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Medical Project Coordinator', 'Coordinate clinical project milestones, documentation, and stakeholders.', 'ClinicalPath', 'Chennai, India', 'CONTRACT', 1, CURRENT_TIMESTAMP, TRUE),
('Biostatistician', 'Design and analyze studies that support evidence-based healthcare decisions.', 'BioMetric Research', 'Hyderabad, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('EdTech Curriculum Designer', 'Create project-based learning experiences for technology learners.', 'LearnLoop', 'Remote - India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Instructional Designer', 'Build engaging digital courses with measurable learning outcomes.', 'CourseCraft', 'Bengaluru, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Academic Partnerships Manager', 'Develop partnerships with universities and professional learning communities.', 'CampusBridge', 'Delhi NCR, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Student Success Advisor', 'Coach learners through goals, milestones, and career transitions.', 'Pathway Learning', 'Pune, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Education Data Analyst', 'Build dashboards and insights that improve learner engagement and outcomes.', 'EduSignal', 'Hyderabad, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Mobile Android Developer', 'Build polished Android experiences with Kotlin and modern architecture.', 'AppHarbor', 'Bengaluru, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('iOS Developer', 'Create reliable Swift applications with strong usability and performance.', 'PocketWorks', 'Remote - India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Flutter Engineer', 'Ship cross-platform mobile features with Flutter and clean architecture.', 'CrossPlatform Labs', 'Chennai, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Mobile QA Engineer', 'Test mobile applications across devices, networks, and release cycles.', 'DeviceLoop', 'Pune, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Game Designer', 'Design engaging mechanics, progression systems, and player experiences.', 'PlayForge', 'Bengaluru, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Game Developer', 'Implement gameplay systems and tools using Unity and C#.', 'PixelQuest', 'Hyderabad, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('3D Artist', 'Create optimized 3D assets and environments for interactive experiences.', 'RenderHouse', 'Remote - India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Technical Artist', 'Bridge art and engineering through shaders, pipelines, and optimization.', 'VisualEngine', 'Pune, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Blockchain Developer', 'Build secure smart contracts and services for digital asset products.', 'ChainBridge', 'Bengaluru, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Web3 Product Analyst', 'Research decentralized product ecosystems and user behavior.', 'LedgerVerse', 'Remote - India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('IoT Solutions Engineer', 'Connect devices, platforms, and analytics for industrial customers.', 'DeviceMesh', 'Chennai, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Embedded Systems Engineer', 'Develop reliable firmware and device integrations for connected products.', 'CircuitWorks', 'Pune, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Robotics Software Engineer', 'Build perception, planning, and control software for autonomous systems.', 'RoboMotion', 'Bengaluru, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Hardware Validation Engineer', 'Validate electronics through test automation and production readiness.', 'SiliconTrail', 'Hyderabad, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Renewable Energy Analyst', 'Analyze clean-energy projects, markets, and investment opportunities.', 'GreenCurrent', 'Mumbai, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Sustainability Consultant', 'Help organizations measure emissions and deliver practical sustainability plans.', 'Earthwise Advisory', 'Remote - India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Environmental Data Scientist', 'Use geospatial and environmental data to guide climate action.', 'EcoSignal', 'Bengaluru, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Energy Project Manager', 'Deliver solar and storage projects from planning through commissioning.', 'SunGrid Energy', 'Pune, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Technical Writer', 'Create precise developer documentation for APIs and platform workflows.', 'DocsMatter', 'Remote - India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Developer Advocate', 'Help developers succeed through examples, talks, and open-source engagement.', 'DevRelWorks', 'Bengaluru, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Solutions Engineer', 'Partner with sales and customers to demonstrate technical product value.', 'DemoCraft', 'Delhi NCR, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Research Engineer', 'Prototype and evaluate new approaches for applied technology problems.', 'Applied Futures', 'Hyderabad, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Technical Recruiter', 'Partner with engineering leaders to hire high-impact technical teams.', 'HireSignal', 'Remote - India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Operations Research Analyst', 'Apply optimization and simulation to improve complex decisions.', 'DecisionLab', 'Bengaluru, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Customer Insights Analyst', 'Combine research and behavioral data to explain customer needs.', 'VoiceOfUser', 'Mumbai, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Digital Transformation Consultant', 'Guide organizations through technology modernization and operating-model change.', 'ModernizeIQ', 'Pune, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Project Coordinator', 'Keep cross-functional projects organized through plans, updates, and follow-through.', 'ExecutionPoint', 'Chennai, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE),
('Office and Facilities Manager', 'Create efficient, welcoming workplaces and manage facilities operations.', 'WorkplaceCo', 'Bengaluru, India', 'FULL_TIME', 1, CURRENT_TIMESTAMP, TRUE);